# Dependencies
markdown:         rdiscount
highlighter:      pygments

# Permalinks
permalink:        pretty

# Server
destination:      ./compiled-docs/
exclude:          [".gitignore"]
port:             9002
baseurl:          /floatThead/

# Site vars
base_url:         "/floatThead"

js_url:           /floatThead/dist/jquery.floatThead.js
